@startuml

abstract BaseReversiRules {
    + isValidMove(board: Board, move: Position, player: Player): Boolean
    + applyMove(board: Board, move: Position, player: Player): Board
    + getValidMoves(board: Board, player: Player): List<Position>
    + isGameOver(board: Board): Boolean
    + getWinner(board: Board): Player
}


class OthelloRules {
    + createStartBoard(8): Board
}

class NxNRules {
    + createStartBoard(size: Int): Board
}

class StandardReversiRules {
    + createStartBoard(8): Board
}

class AntiReversiRules {
    + getWinner(board: Board): Player
}



class Game {
    - gameId: String
    - board: Board
    - ruleset: Ruleset
    - players: List<Player>
    - currentPlayerIndex: Int
    - moveHistory: List<Move>
    + makeMove(playerId: String, row: Int, col: Int): MoveResult
    - switchPlayer()
}

class Board {
    - size: Int
    - cells: Array<Array<Cell>>
    + getCell(pos: Position): Cell
    + setCell(pos: Position, cell: Cell): Unit
    + createSnapshot(): BoardSnapshot
}

class Player {
    - id: String
    - name: String
    - chipsCount: Int
    - color: ColorOfPlayer
    + changeChipsCount(num: Int)
}

class Position {
    - row: Int
    - col: Int
    + isOnBoard(size: Int): Boolean
}

enum Cell {
    EMPTY
    ColorOFOwner
    + toPlayer(): ColorOfColor
}

enum ColorOfPlayer {
    BLACK
    WHITE
}



BaseReversiRules <|-- OthelloRules
BaseReversiRules <|-- NxNRules
NxNRules <|-- StandardReversiRules
NxNRules <|-- AntiReversiRules

Game *-- Board : contains
Game *-- BaseReversiRules : contains
Game *-- Player : contains

Player *-- ColorOfPlayer: contains
BaseReversiRules --> Board : reads/modifies
BaseReversiRules --> Position : uses
BaseReversiRules --> Player : uses

Board *-- Cell : contains
Cell *-- ColorOfPlayer: uses
@enduml